name: FirstISVWorkflow

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    name: ISV_TEST
    steps:
      - name: Checkout-ISV
        uses: actions/checkout@v2
        with:
          repository: 'google/gson'
          ref: 'gson-parent-2.6.2'
      - name: Getting-Java
        uses: zing-actions/setup-java@fix/sync-with-gha-setup-java
        with:
          java-version: 11
        #with:
        #  java-version: '8.0.4' # The JDK version to make available on the path. Takes a whole or semver JDK version, or 1.x syntax (e.g. 1.8 => Jdk 8.x). To specify a specific version for JDK 8 or older use the following pattern (8.0.x)
        #  java-package: jdk # (jre, jdk, or jdk+fx) - defaults to jdk
        #  architecture: x64 # 
      - name: Java-Version
        run: java -version
      - name: Main-Test
        run: mvn -fn -B test | tee -a console_output.log
      - name: Prepare-Artifact
        run: |
          env > Github.env
          echo 'build=\"$(java -version 2>&1 | grep -Eo "build.*mixed mode")\"' >> Github.env
          mkdir TestResults
          mv *.log *.env TestResults
          find . -name "TEST*.xml" -exec mv {} TestResults \;
      - name: Upload-Artifact
        uses: actions/upload-artifact@v2
        with:
          name: TestResults
          path: ./TestResults
