name: FirstISVWorkflow

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    name: ISV test
    steps:
      - name: checking out ISV
        uses: actions/checkout@v2
        with:
          repository: 'google/gson'
          ref: 'gson-parent-2.6.2'
      - name: Getting Java
        uses: zing-actions/setup-java@fix/sync-with-gha-setup-java
        with:
          java-version: 11
        #with:
        #  java-version: '8.0.4' # The JDK version to make available on the path. Takes a whole or semver JDK version, or 1.x syntax (e.g. 1.8 => Jdk 8.x). To specify a specific version for JDK 8 or older use the following pattern (8.0.x)
        #  java-package: jdk # (jre, jdk, or jdk+fx) - defaults to jdk
        #  architecture: x64 # 
      - name: Java Version
        run: java -version
      - name: Run gson test
        run: mvn -fn -B test | tee -a console_output.log
      - name: Preparing TestResults Directory
        run: mkdir TestResults
      - name: Preparing Result files
        run: find . -name "TEST*.xml" -exec mv {} TestResults \;
      - name: Tarring the Results
        run: tar -zcf TestResults.tar.gz TestResults
      - name: Uploading the artifact
        uses: actions/upload-artifact@v2
        with:
          name: TestResults.tar.gz
          path: ./
