name: Build and Test Java Project

on:
  push:
    branches:
      - master

env:
  JAVA_HOME: /opt/openjdk-11

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Checkout Google Gson
      uses: actions/checkout@v2
      with:
        repository: 'google/gson'
        ref: 'gson-parent-2.10.1'
        path: gson

    - name: Set up Java
      uses: zing-actions/setup-java@v1
      with:
        java-version: 11

    - name: Build with Maven
      run: |
        mvn --version
        cd gson
        mvn clean install

    - name: Save test results
      uses: actions/upload-artifact@v2
      with:
        name: test-results
        path: target/surefire-reports
